export const baseUrl = "https://localhost:44330/api";
export const imgUrl = "https://localhost:44330/img";

// User Authentication
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

// User
export const GET_USER_SUCCESS = "GET_USER_SUCCES";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const GET_USER_IMAGES_SUCCESS = "GET_USER_IMAGES_SUCCESS";
export const GET_USER_IMAGES_ERROR = "GET_USER_IMAGES_ERROR";

export const GET_HEADINGS_COUNT_SUCCESS = "GET_HEADINGS_COUNT_SUCCESS";
export const GET_HEADINGS_COUNT_ERROR = "GET_HEADINGS_COUNT_ERROR";

export const UPDATE_USER_SUCCES = "UPDATE_USER_SUCCES";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const CHANGE_AVATAR_SUCCES = "CHANGE_AVATAR_SUCCES";
export const CHANGE_AVATAR_ERROR = "CHANGE_AVATAR_ERROR";

export const CHANGE_COVER_SUCCES = "CHANGE_COVER_SUCCES";
export const CHANGE_COVER_ERROR = "CHANGE_COVER_ERROR";

export const CHECK_FOLLOW_SUCCESS = "CHECK_FOLLOW_SUCCESS";
export const CHECK_FOLLOW_ERROR = "CHECK_FOLLOW_ERROR";

export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS";
export const FOLLOW_USER_ERROR = "FOLLOW_USER_ERROR";

export const UNFOLLOW_USER_SUCCESS = "UNFOLLOW_USER_SUCCESS";
export const UNFOLLOW_USER_ERROR = "UNFOLLOW_USER_ERROR";

export const GET_FOLLOWERS_SUCCESS = "GET_FOLLOWERS_SUCCESS";
export const GET_FOLLOWERS_ERROR = "GET_FOLLOWERS_ERROR";

export const CHECK_FOLLOW_RANGE_SUCCESS = "CHECK_FOLLOW_RANGE_SUCCESS";
export const CHECK_FOLLOW_RANGE_ERROR = "CHECK_FOLLOW_RANGE_ERROR";

export const GET_FOLLOWEE_SUCCESS = "GET_FOLLOWEE_SUCCESS";
export const GET_FOLLOWEE_ERROR = "GET_FOLLOWEE_ERROR";

export const CHECK_FOLLOWEE_RANGE_SUCCESS = "CHECK_FOLLOWEE_RANGE_SUCCESS";
export const CHECK_FOLLOWEE_RANGE_ERROR = "CHECK_FOLLOWEE_RANGE_ERROR";

export const SEARCH_USERS_SUCCESS = "SEARCH_USERS_SUCCESS";
export const SEARCH_USERS_ERROR = "SEARCH_USERS_ERROR";

// Channel

export const GET_CHANNELS_SUCCES = "GET_CHANNELS_SUCCES";
export const GET_CHANNELS_ERROR = "GET_CHANNELS_ERROR";

// Heading

export const POST_HEADING_SUCCES = "POST_HEADING_SUCCES";
export const POST_HEADING_ERROR = "POST_HEADING_ERROR";

export const GET_HEADING_FOR_USER_SUCCES = "GET_HEADING_FOR_USER_SUCCES";
export const GET_HEADING_FOR_USER_ERROR = "GET_HEADING_FOR_USER_ERROR";

export const GET_HEADING_IMAGES_SUCCESS = "GET_HEADING_IMAGES_SUCCESS";
export const GET_HEADING_IMAGES_ERROR = "GET_HEADING_IMAGES_ERROR";

export const GET_HEADING_SUCCES = "GET_HEADING_SUCCES";
export const GET_HEADING_ERROR = "GET_HEADING_ERROR";

export const GET_BROWSE_HEADING_SUCCESS = "GET_BROWSE_HEADING_SUCCESS";
export const GET_BROWSE_HEADING_ERROR = "GET_BROWSE_HEADING_ERROR";

export const GET_BROWSE_FOLLOWING_SUCCESS = "GET_BROWSE_FOLLOWING_SUCCESS";
export const GET_BROWSE_FOLLOWING_ERROR = "GET_BROWSE_FOLLOWING_ERROR";

export const ADD_HEADING_IMAGE_SUCCES = "ADD_HEADING_IMAGE_SUCCES";
export const ADD_HEADING_IMAGE_ERROR = "ADD_HEADING_IMAGE_ERROR";

export const HANDLE_LIKE_SUCCESS = "HANDLE_LIKE_SUCCESS";
export const HANDLE_LIKE_ERROR = "HANDLE_LIKE_ERROR";

export const SEARCH_HEADING_SUCCESS = "SEARCH_HEADING_SUCCESS";
export const SEARCH_HEADING_ERROR = "SEARCH_HEADING_ERROR";

export const GET_FOR_CHANNEL_SUCCESS = "GET_FOR_CHANNEL_SUCCESS";
export const GET_FOR_CHANNEL_ERROR = "GET_FOR_CHANNEL_ERROR";

export const SEARCH_FOR_CHANNEL_SUCCESS = "SEARCH_FOR_CHANNEL_SUCCESS";
export const SEARCH_FOR_CHANNEL_ERROR = "SEARCH_FOR_CHANNEL_ERROR";

export const GET_TRENDS_SUCCESS = "GET_TRENDS_SUCCESS";
export const GET_TRENDS_ERROR = "GET_TRENDS_ERROR";

export const REMOVE_HEADING_SUCCESS = "REMOVE_HEADING_SUCCESS";
export const REMOVE_HEADING_ERROR = "REMOVE_HEADING_ERROR";

// comment

export const COMMENT_GET_SUCCESS = "COMMENT_GET_SUCCESS";
export const COMMENT_GET_ERROR = "COMMENT_GET_ERROR";

export const GET_COMMENT_USER_IMAGES_SUCCESS =
  "GET_COMMENT_USER_IMAGES_SUCCESS";
export const GET_COMMENT_USER_IMAGES_ERROR = "GET_COMMENT_USER_IMAGES_ERROR";

export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_ERROR = "POST_COMMENT_ERROR";

// reply

export const REPLY_GET_SUCCESS = "REPLY_GET_SUCCESS";
export const REPLY_GET_ERROR = "REPLY_GET_ERROR";

export const POST_REPLY_SUCCESS = "POST_REPLY_SUCCESS";
export const POST_REPLY_ERROR = "POST_REPLY_ERROR";
